# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout #adds files to circle CI
      - hello:
          name: Testing First Step and Viewing Files
          command: |
            uname -a
            echo "Hello, Arm!"
            ls -al
      - run_tests:
          name: Running Tests
          command: |
            cd transcribvr
            python3 -m pytest tests

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - build